import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          <section className="gabAIContainer">
            <div className="gabAIBackground">
              <div className="gabAIContentMobile">
                <div className="gabAIContentMobileHand">
                  <b
                    className="gabAIText ms-2 mt-3"
                    style={{
                      letterSpacing: "2px",
                      paddingLeft: "4vw",
                      paddingTop: "4vw",
                    }}
                  >
                    IN DEVELOPMENT
                  </b>
                  <img
                    className="gabAILogo ms-2"
                    src="/GabAI-LogoTrim.webp"
                    style={{ paddingLeft: "4vw" }}
                  />
                  <p
                    className="gabAIText  ms-2 mb-0"
                    style={{ paddingLeft: "4vw" }}
                  >
                    We believe education should keep up with the speed of
                    technological advancements.
                  </p>
                </div>

                <p
                  className="gabAIText  ms-2"
                  style={{ paddingLeft: "4vw", paddingBottom: "4vw" }}
                >
                  One of our upcoming projects is the use of Artificial
                  Intelligence in developing curriculums and lesson plans, to
                  enhance teacher and student learning.
                </p>
              </div>
              <div className="gabAIHandContainer">
                <div className="gabAIHand">
                  <div className="gabAIContent">
                    <b
                      className="gabAIText  ms-5"
                      style={{ letterSpacing: "5px" }}
                    >
                      IN DEVELOPMENT
                    </b>
                    <img
                      className="gabAILogo ms-5"
                      src="/GabAI-LogoTrim.webp"
                    />
                    <p className="gabAIText ms-5">
                      We believe education should keep up with the speed of
                      technological advancements. One of our upcoming projects
                      is the use of Artificial Intelligence in developing
                      curriculums and lesson plans, to enhance teacher and
                      student learning.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className="Hero1Container">
            <div className="d-flex flex-column justify-content-center align-items-center w-100 h-100">
              <h1>HERO 1</h1>
            </div>
          </section>
        </div>
      </main>
    </>
  );
}
